# Generated by Django 4.1.1 on 2024-12-05 07:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directorio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Business Category',
                'verbose_name_plural': 'Business Categories',
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_rate', models.FloatField(default=0, verbose_name='exchange rate')),
                ('distributor_gain', models.FloatField(default=0, verbose_name='distributor gain')),
                ('delivery_distance_price', models.IntegerField(default=0, verbose_name='delivery distance price')),
                ('delivery_fixed_price', models.IntegerField(default=300, verbose_name='delivery fixed price')),
            ],
            options={
                'verbose_name': 'configuration',
                'verbose_name_plural': 'configurations',
            },
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_image', models.ImageField(blank=True, null=True, upload_to='distributors/vehicles', verbose_name='vehicle image')),
                ('vehicle_id', models.CharField(max_length=7, verbose_name='vehicle registration id')),
                ('vehicle_type', models.CharField(max_length=20, verbose_name='vehicle type')),
                ('is_online', models.BooleanField(verbose_name='is online')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'distributor',
                'verbose_name_plural': 'distributors',
            },
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Metrics',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='date')),
                ('time', models.TimeField(auto_now=True, verbose_name='time')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('assigned', 'assigned'), ('on the way', 'on the way'), ('delivered', 'delivered'), ('canceled', 'canceled')], max_length=15, verbose_name='status')),
                ('pay_type', models.CharField(max_length=25, verbose_name='pay_type')),
                ('was_paid_by_distributor', models.BooleanField(default=False, verbose_name='was paid by distributor')),
                ('delivery_total_distance', models.IntegerField(verbose_name='delivery total distance')),
                ('delivery_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='api_orders', to='directorio.address', verbose_name='delivery address')),
                ('distributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.distributor', verbose_name='distributor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='price')),
                ('time', models.CharField(max_length=10, verbose_name='time of preparation')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='image')),
                ('um', models.CharField(max_length=10, verbose_name='unit of measurement')),
                ('amount', models.IntegerField(verbose_name='amount')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('address', models.CharField(max_length=150, verbose_name='address')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurants', verbose_name='image')),
                ('time', models.CharField(max_length=10, verbose_name='time')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('tax', models.FloatField(default=10, verbose_name='tax')),
                ('latitude', models.CharField(default='', max_length=25, verbose_name='latitude')),
                ('longitude', models.CharField(default='', max_length=25, verbose_name='longitude')),
                ('recommended', models.BooleanField(default=False, verbose_name='recommended')),
                ('funds', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='funds')),
                ('bussiness_type', models.ManyToManyField(to='api.category', verbose_name='Business type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'restaurant',
                'verbose_name_plural': 'restaurants',
            },
        ),
        migrations.CreateModel(
            name='RestaurantRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'at least 1'), django.core.validators.MaxValueValidator(5, 'max 5')], verbose_name='rating')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.restaurant', verbose_name='restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'restaurant rating',
                'verbose_name_plural': 'restaurant ratings',
            },
        ),
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'at least 1'), django.core.validators.MaxValueValidator(5, 'max 5')], verbose_name='rating')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product', verbose_name='product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'product rating',
                'verbose_name_plural': 'product ratings',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='name')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.restaurant', verbose_name='business')),
            ],
            options={
                'verbose_name': 'product category',
                'verbose_name_plural': 'product categories',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.productcategory', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='product',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.restaurant', verbose_name='restaurant'),
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'at least 1')], verbose_name='amount')),
                ('was_paid_by_business', models.BooleanField(default=False, verbose_name='was paid by business')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order', verbose_name='order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'order detail',
                'verbose_name_plural': 'order details',
            },
        ),
        migrations.CreateModel(
            name='DistributorRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'at least 1'), django.core.validators.MaxValueValidator(5, 'max 5')], verbose_name='rating')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.distributor', verbose_name='distributor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Distributor rating',
                'verbose_name_plural': 'Distributor ratings',
            },
        ),
    ]
