# Generated by Django 4.1.1 on 2023-06-11 22:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductRate',
            new_name='ProductRating',
        ),
        migrations.RenameModel(
            old_name='RestaurantRate',
            new_name='RestaurantRating',
        ),
        migrations.AlterModelOptions(
            name='productrating',
            options={'verbose_name': 'product rating', 'verbose_name_plural': 'product ratings'},
        ),
        migrations.AlterModelOptions(
            name='restaurantrating',
            options={'verbose_name': 'restaurant rating', 'verbose_name_plural': 'restaurant ratings'},
        ),
    ]
