# Generated by Django 4.1.1 on 2024-12-05 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='was_paid_by_business',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, null=True, verbose_name='exchange rate'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='quantity'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True, verbose_name='tax rate'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='unit price'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.order'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.product'),
        ),
    ]
