# Generated by Django 4.1.1 on 2024-12-11 03:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_configuration_business_closing_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='bussiness_type',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='time',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='friday_closing_time',
            field=models.TimeField(default=datetime.time(23, 59), verbose_name='Friday Closing Time'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='friday_opening_time',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name='Friday Opening Time'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='monday_closing_time',
            field=models.TimeField(default=datetime.time(23, 59), verbose_name='Monday Closing Time'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='monday_opening_time',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name='Monday Opening Time'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='saturday_closing_time',
            field=models.TimeField(default=datetime.time(23, 59), verbose_name='Saturday Closing Time'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='saturday_opening_time',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name='Saturday Opening Time'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='sunday_closing_time',
            field=models.TimeField(default=datetime.time(23, 59), verbose_name='Sunday Closing Time'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='sunday_opening_time',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name='Sunday Opening Time'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='thursday_closing_time',
            field=models.TimeField(default=datetime.time(23, 59), verbose_name='Thursday Closing Time'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='thursday_opening_time',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name='Thursday Opening Time'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tuesday_closing_time',
            field=models.TimeField(default=datetime.time(23, 59), verbose_name='Tuesday Closing Time'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tuesday_opening_time',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name='Tuesday Opening Time'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='wednesday_closing_time',
            field=models.TimeField(default=datetime.time(23, 59), verbose_name='Wednesday Closing Time'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='wednesday_opening_time',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name='Wednesday Opening Time'),
        ),
    ]
