# Generated by Django 4.1.1 on 2023-06-15 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_productrating_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='time',
            field=models.CharField(max_length=25, verbose_name='time of preparation'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='phone'),
        ),
    ]
