# Generated by Django 4.1.1 on 2023-06-15 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_product_time_alter_restaurant_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='time',
            field=models.CharField(max_length=10, verbose_name='time of preparation'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='time',
            field=models.CharField(max_length=10, verbose_name='time'),
        ),
    ]
