# Generated by Django 4.1.1 on 2024-12-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_order_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='delivery_time',
            field=models.IntegerField(default=30, verbose_name='delivery time (minutes)'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='time',
            field=models.IntegerField(default=0, verbose_name='time'),
        ),
    ]
