# Generated by Django 4.1.1 on 2024-12-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_configuration_delivery_time_restaurant_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thermopack_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='thermopack price'),
        ),
    ]
