# Generated by Django 4.1.1 on 2023-07-07 15:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_restaurant_tax_alter_restaurant_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributorRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'at least 1'), django.core.validators.MaxValueValidator(5, 'max 5')], verbose_name='rating')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.distributor', verbose_name='distributor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Distributor rating',
                'verbose_name_plural': 'Distributor ratings',
            },
        ),
    ]
