# Generated by Django 4.1.1 on 2024-12-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_order_created_at_alter_orderdetail_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='business_type',
            field=models.ManyToManyField(to='api.category', verbose_name='Business Type'),
        ),
    ]
