# Generated by Django 4.1.1 on 2023-07-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_distributorrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='type',
            field=models.CharField(default='', max_length=50, verbose_name='type'),
            preserve_default=False,
        ),
    ]
