# Generated by Django 4.1.1 on 2024-12-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_restaurant_business_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='closed_days',
            field=models.ManyToManyField(blank=True, to='api.dayofweek', verbose_name='Closed Days'),
        ),
    ]
