# Generated by Django 4.1.1 on 2024-12-15 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_days_of_week'),
        ('api', '0011_dayofweek_restaurant_closed_days'),
    ]

    operations = [
    ]
