# Generated by Django 4.1.1 on 2023-07-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_restaurant_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='latitude',
            field=models.CharField(default='', max_length=25, verbose_name='latitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='longitude',
            field=models.CharField(default='', max_length=25, verbose_name='longitude'),
            preserve_default=False,
        ),
    ]
