# Generated by Django 4.1.1 on 2023-07-20 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_restaurant_latitude_alter_restaurant_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_rate', models.FloatField(verbose_name='exchange rate')),
            ],
            options={
                'verbose_name': 'configuration',
                'verbose_name_plural': 'configurations',
            },
        ),
        migrations.AddField(
            model_name='distributor',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='is online'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='amount'),
            preserve_default=False,
        ),
    ]
