# Generated by Django 4.1.1 on 2023-07-22 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_address_order_delivery_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_type',
            field=models.CharField(default='', max_length=25, verbose_name=''),
            preserve_default=False,
        ),
    ]
