# Generated by Django 4.1.1 on 2023-07-27 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.distributor', verbose_name='distributor'),
        ),
    ]
