# Generated by Django 4.1.1 on 2023-07-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_order_distributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_type',
            field=models.CharField(max_length=25, verbose_name='pay_type'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('assigned', 'assigned'), ('on the way', 'on the way'), ('delivered', 'delivered')], max_length=15, verbose_name='status'),
        ),
    ]
