# Generated by Django 4.1.1 on 2023-08-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='was_paid_by_business',
            field=models.BooleanField(default=False, verbose_name='was paid by business'),
        ),
    ]
