# Generated by Django 4.1.1 on 2023-08-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_orderdetail_was_paid_by_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='distributor_gain',
            field=models.FloatField(default=0, verbose_name='distributor gain'),
        ),
    ]
