# Generated by Django 4.1.1 on 2023-08-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_configuration_distributor_gain'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='was_paid_by_distributor',
            field=models.BooleanField(default=False, verbose_name='was paid by distributor'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('assigned', 'assigned'), ('on the way', 'on the way'), ('delivered', 'delivered'), ('canceled', 'canceled')], max_length=15, verbose_name='status'),
        ),
    ]
