# Generated by Django 4.1.1 on 2023-08-13 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_restaurant_recommended'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='categories_product',
            new_name='bussiness_type',
        ),
    ]
