# Generated by Django 4.1.1 on 2023-08-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_productcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Metrics',
                'verbose_name_plural': 'Metrics',
            },
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='bussiness_type',
            field=models.ManyToManyField(to='api.category', verbose_name='Business type'),
        ),
    ]
