# Generated by Django 4.1.1 on 2023-08-22 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_metrics_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='type',
        ),
    ]
