# Generated by Django 4.1.1 on 2023-09-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_category_options_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='delivery_distance_price',
            field=models.IntegerField(default=0, verbose_name='delivery distance price'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='delivery_fixed_price',
            field=models.IntegerField(default=300, verbose_name='delivery fixed price'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_total_distance',
            field=models.IntegerField(default=0, verbose_name='delivery total distance'),
            preserve_default=False,
        ),
    ]
