# Generated by Django 4.1.1 on 2023-06-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='imagen',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/', verbose_name='imagen'),
        ),
    ]
