# Generated by Django 4.1.1 on 2023-08-13 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0002_remove_user_imagen_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='name')),
                ('details', models.CharField(max_length=240, verbose_name='details')),
                ('long', models.CharField(max_length=50, verbose_name='longitude')),
                ('lat', models.CharField(max_length=50, verbose_name='latitude')),
                ('receiver_name', models.CharField(blank=True, max_length=80, null=True, verbose_name='reciever name')),
                ('phone', models.CharField(blank=True, max_length=18, null=True, verbose_name='phone number')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
            },
        ),
    ]
