# Generated by Django 4.1.1 on 2024-12-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0003_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
    ]
