name: Actualizar en VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Conectar al VPS y actualizar
        uses: appleboy/ssh-action@master
        with:
          host: 207.244.233.96
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd rdlv
            git pull
            source venv/bin/activate
            pip install -r requirements.txt
            python manage.py migrate
            python manage.py collectstatic
            sudo service gunicorn restart
            sudo service nginx restart